{{- if .Values.artifacts.s3.createSecret.accessKeyID -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.artifactCredentialName" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.artifacts.s3.createSecret.accessKeyID | toString | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.artifacts.s3.createSecret.secretAccessKey | toString | b64enc | quote }}
  {{- if .Values.artifacts.s3.createSecret.endpointUrl }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.artifacts.s3.createSecret.endpointUrl | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.artifacts.s3.createSecret.defaultRegion }}
  AWS_DEFAULT_REGION: {{ .Values.artifacts.s3.createSecret.defaultRegion | toString | b64enc | quote }}
  {{- end -}}
  {{- if .Values.artifacts.s3.createSecret.ignoreTls }}
  MLFLOW_S3_IGNORE_TLS: {{ .Values.artifacts.s3.createSecret.ignoreTls | toString | b64enc | quote }}
  {{- end }}
{{- end -}}
