{{ $args := list (include "mlflow.enableTracking" .) 
                  (include "mlflow.enableTracking" .) 
                  (include "mlflow.serverPort" .) 
                  (include "mlflow.serverWorkers" .) 
                  (include "mlflow.serverMetrics" .) 
                  (include "mlflow.proxyArtifacts" .) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - mlflow
            - server
            - --host=0.0.0.0
            - --backend-store-uri=$(BACKEND_STORE_URI)
            - --default-artifact-root=$(DEFAULT_ARTIFACT_ROOT)
            {{- range $args }}
            {{- if . }}
            - {{ . }}
            {{- end }}
            {{- end }}
          env:
            {{- include "mlflow.defaultArtifactRootEnvironment" . | nindent 12 }}
            - name: BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backendStore.existingSecret }}
                  key: BACKEND_STORE_URI
                  optional: false
          {{- if (include "mlflow.artifactEnvironmentFromSecret" .) }}
          envFrom:
          {{- include "mlflow.artifactEnvironmentFromSecret" . | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.trackingServer.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if (include "mlflow.s3CaBundleVolumeMount" .) }}
          volumeMounts:
          {{- include "mlflow.s3CaBundleVolumeMount" . | nindent 10 }}
          {{- end }}
      {{- if (include "mlflow.s3CaBundleVolume" .) }}
      volumes:
        {{- include "mlflow.s3CaBundleVolume" . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
